/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.ling.prog;

import java.awt.Color;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Guilherme
 */
public class Tela extends javax.swing.JFrame {

    // VALORES MÍNIMOS
    Integer minCpu = 100;
    Integer minDisco = 100;
    Integer minMemoria = 100;
    
    // VALORES MÁXIMOS
    Integer maxCpu = 0;
    Integer maxDisco = 0;
    Integer maxMemoria = 0;
    
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prgCpu = new javax.swing.JProgressBar();
        prgDisco = new javax.swing.JProgressBar();
        prgMemoria = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAcao = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblMinimoCpu = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblMaximoCpu = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMinimoDisco = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblMaximoDisco = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblMinimoMemoria = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblMaximoMemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("DESEMPENHO DO COMPUTADOR");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("CPU");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("DISCO");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("MEMÓRIA");

        jLabel5.setText("2.3 GHz");

        jLabel6.setText("3.10 GHz");

        jLabel7.setText("0%");

        jLabel8.setText("100%");

        jLabel9.setText("0 GB");

        jLabel10.setText("8 GB");

        btnAcao.setText("Fazer leitura dos dados");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        jLabel11.setText("Mín:");

        lblMinimoCpu.setText("0");

        jLabel15.setText("Máx:");

        lblMaximoCpu.setText("0");

        jLabel12.setText("Mín:");

        lblMinimoDisco.setText("0");

        jLabel16.setText("Máx:");

        lblMaximoDisco.setText("0");

        jLabel17.setText("Mín:");

        lblMinimoMemoria.setText("0");

        jLabel19.setText("Máx:");

        lblMaximoMemoria.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcao)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(lblMinimoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMaximoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prgMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prgCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(prgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMinimoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMaximoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMinimoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMaximoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(prgCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblMinimoCpu)
                    .addComponent(jLabel15)
                    .addComponent(lblMaximoCpu))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7)))
                                    .addComponent(prgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMinimoDisco)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16)
                                    .addComponent(lblMaximoDisco))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prgMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblMaximoMemoria)
                    .addComponent(jLabel17)
                    .addComponent(lblMinimoMemoria))
                .addGap(18, 18, 18)
                .addComponent(btnAcao)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        
        // GERAR DADOS DO COMPUTADOR
        Integer aleatorioCpu = ThreadLocalRandom.current().nextInt(0,100);
        Integer aleatorioDisco = ThreadLocalRandom.current().nextInt(0,100);
        Integer aleatorioMemoria = ThreadLocalRandom.current().nextInt(0,100);
        
        // CONVERSÃO DA PORCENTAGEM
        Double converterCpu = aleatorioCpu.doubleValue();
        Double converterMemoria = aleatorioMemoria.doubleValue();
        
        // CÁLCULO DA FREQUÊNCIA
        Double resultadoCpu = (converterCpu * 0.008) + 2.3;
        Double resultadoMemoria = converterMemoria * 0.08;
        
        // PORCENTAGEM DE USO
        prgCpu.setStringPainted(true);
        prgCpu.setString(String.format("%d %% (%.2f GHz)",
                aleatorioCpu, resultadoCpu));
        prgCpu.setForeground(Color.black);
        
        prgDisco.setStringPainted(true);
        prgDisco.setString(String.format("%d %%", aleatorioDisco));
        prgDisco.setForeground(Color.black);
        
        prgMemoria.setStringPainted(true);
        prgMemoria.setString(String.format("%d %% (%.2f GB)",
                aleatorioMemoria, resultadoMemoria));
        prgMemoria.setForeground(Color.black);
        
        // ATUALIZAÇÃO DA BARRA DE PROGRESSO
        prgCpu.setValue(aleatorioCpu);
        prgDisco.setValue(aleatorioDisco);
        prgMemoria.setValue(aleatorioMemoria);
        
        // VALIDAÇÃO VALORES MÍNIMOS
        if (aleatorioCpu < minCpu){
            minCpu = aleatorioCpu;
            Double minFreqCpu = (minCpu * 0.008) + 2.3;
            lblMinimoCpu.setText(String.format("%d %% (%.2f GHz)",
                minCpu, minFreqCpu));
        }
        if (aleatorioDisco < minDisco){
            minDisco = aleatorioDisco;
            lblMinimoDisco.setText(String.format("%d %%", minDisco));
        }
        if (aleatorioMemoria < minMemoria){
            minMemoria = aleatorioMemoria;
            Double minFreqMemoria = minMemoria * 0.08;
            lblMinimoMemoria.setText(String.format("%d %% (%.2f GB)",
                minMemoria, minFreqMemoria));
        }
        
        // VALIDAÇÃO VALORES MÁXIMOS
        if (aleatorioCpu > maxCpu){
            maxCpu = aleatorioCpu;
            Double maxFreqCpu = (maxCpu * 0.008) + 2.3;
            lblMaximoCpu.setText(String.format("%d %% (%.2f GHz)",
                maxCpu, maxFreqCpu));
        }
        if (aleatorioDisco > maxDisco){
            maxDisco = aleatorioDisco;
            lblMaximoDisco.setText(String.format("%d %%", maxDisco));
        }
        if (aleatorioMemoria > maxMemoria){
            maxMemoria = aleatorioMemoria;
            Double maxFreqMemoria = maxMemoria * 0.08;
            lblMaximoMemoria.setText(String.format("%d %% (%.2f GB)",
                maxMemoria, maxFreqMemoria));
        }
    }//GEN-LAST:event_btnAcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMaximoCpu;
    private javax.swing.JLabel lblMaximoDisco;
    private javax.swing.JLabel lblMaximoMemoria;
    private javax.swing.JLabel lblMinimoCpu;
    private javax.swing.JLabel lblMinimoDisco;
    private javax.swing.JLabel lblMinimoMemoria;
    private javax.swing.JProgressBar prgCpu;
    private javax.swing.JProgressBar prgDisco;
    private javax.swing.JProgressBar prgMemoria;
    // End of variables declaration//GEN-END:variables
}
